cot: false
input_path: delta_belief_rl/env/twenty_questions/config/grok/
output_path: delta_belief_rl/env/twenty_questions/direct/grok/
system_prompt:
  original: true
data:
  train:
    input_name: rl_training.txt
    output_name: rl_training.parquet
    N: -1
  test:
    input_name: test.txt
    output_name: test.parquet
    N: -1
