cot: false
json_path: delta_belief_rl/env/murder_mystery/config/paprika/murder_mystery.json
input_path: delta_belief_rl/env/murder_mystery/config/paprika/
output_path: delta_belief_rl/env/murder_mystery/direct/paprika/
system_prompt:
  original: true
data:
  test:
    output_name: test.parquet
    N: -1
